# Generated by Django 5.2.15 on 2026-06-09 08:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publishDate'], 'verbose_name': 'AI 资讯', 'verbose_name_plural': 'AI 资讯'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='publish_date',
            new_name='publishDate',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary',
        ),
        migrations.AddField(
            model_name='news',
            name='newType',
            field=models.CharField(choices=[('企业要闻', '企业要闻'), ('前沿科技', '前沿科技'), ('通知公告', '通知公告')], default='前沿科技', max_length=50, verbose_name='新闻类型'),
        ),
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='新闻封面'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文内容'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
