# Generated by Django 5.2.14 on 2026-06-11 14:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="联系人/企业名称"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("email", models.EmailField(max_length=254, verbose_name="电子邮箱")),
                ("requirement", models.TextField(verbose_name="算力需求/业务描述")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contact_docs/",
                        verbose_name="附件文档",
                    ),
                ),
                (
                    "submit_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="提交时间"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
            ],
            options={
                "verbose_name": "接入咨询工单",
                "verbose_name_plural": "接入咨询工单",
                "ordering": ["-submit_date"],
            },
        ),
    ]
