# Generated by Django 5.2.15 on 2026-06-09 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('productType', models.CharField(choices=[('认知大模型', '认知大模型陣列'), ('分布式算力', '分布式算力網絡'), ('隐私计算', '隐私计算与安全盾')], default='认知大模型', max_length=50, verbose_name='算力品类')),
                ('price', models.CharField(default='按需计费 (Token)', max_length=50, verbose_name='算力资费')),
                ('description', models.TextField(verbose_name='功能核心描述')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='算力展示长图')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上线发布时间')),
            ],
            options={
                'verbose_name': 'AI 算力矩阵',
                'verbose_name_plural': 'AI 算力矩阵',
                'ordering': ['-publishDate'],
            },
        ),
    ]
